### ISSUE TITLE
El bot registra comandos solo cuando inicia

### ISSUE THREAD

**Issue by RafaelMoralesV** [exdevutem/discord_bot#2]
Al agregar el bot a un servidor nuevo este no registra los comandos dentro del 'nuevo servidor'
para que haga este registro se necesita que se reinicie el bot desde cero

Se recomienda cambiar el handler para que estos cambios ocurran bajo otro evento.

**Comment by RafaelMoralesV** [comment]
Adicionalmente, el bot solo reconoce la id de la guild que esta en el archivo .env
Debe poder registrar guilds de alguna forma, quizas en una bdd?? cosa de poder registrar cambios a los comandos en cualquier compilacion.

**Comment by aaguirreu** [comment]
> Adicionalmente, el bot solo reconoce la id de la guild que esta en el archivo .env Debe poder registrar guilds de alguna forma, quizas en una bdd?? cosa de poder registrar cambios a los comandos en cualquier compilacion.

fixed [aquí](https://github.com/exdevutem/discord_bot/commit/8eb4745b5f2c38403afa538cc53a23437fc906ac)

**Comment by RafaelMoralesV** [comment]
Resuelto en la PR #4
